import { IQuestion } from "../../definitions";

export const mockQuestion: IQuestion = {
  _id: "",
  createdAt: new Date(),
  creatorId: "1",
  description: "test-description-123",
  lm: new Date(),
  rid: "test-rid-123",
  status: "closed",
  subject: "Hist",
  title: "test-title-123",
};

export const mockQuestionsList: IQuestion[] = [
  {
    _id: "1",
    createdAt: new Date(),
    creatorId: "123",
    description: "test-description-1-1",
    lm: new Date(),
    rid: "test-rid-1-1",
    status: "in_progress",
    subject: "Math",
    title: "test-title-1-1",
  },
  {
    _id: "2",
    createdAt: new Date(),
    creatorId: "123",
    description: "test-description-1-2",
    lm: new Date(),
    rid: "test-rid-1-2",
    status: "pending",
    subject: "Math",
    title: "test-title-1-2",
  },
  {
    _id: "3",
    createdAt: new Date(),
    creatorId: "1",
    description: "test-description-2-1",
    lm: new Date(),
    rid: "test-rid-2-1",
    status: "closed",
    subject: "Bio",
    title: "test-title-2-1",
  },
  {
    _id: "4",
    createdAt: new Date(),
    creatorId: "2",
    description: "test-description-2-2",
    lm: new Date(),
    rid: "test-rid-2-2",
    status: "closed",
    subject: "Bio",
    title: "test-title-2-2",
  },
  {
    _id: "5",
    createdAt: new Date(),
    creatorId: "2",
    description: "test-description-3-1",
    lm: new Date(),
    rid: "test-rid-3-1",
    status: "closed",
    subject: "Philo",
    title: "test-title-3-1",
  },
  {
    _id: "6",
    createdAt: new Date(),
    creatorId: "2",
    description: "test-description-3-2",
    lm: new Date(),
    rid: "test-rid-3-2",
    status: "closed",
    subject: "Philo",
    title: "test-title-3-2",
  },
  {
    _id: "7",
    createdAt: new Date(),
    creatorId: "1",
    description: "test-description-4-1",
    lm: new Date(),
    rid: "test-rid-4-1",
    status: "closed",
    subject: "Port",
    title: "test-title-4-1",
  },
  {
    _id: "8",
    createdAt: new Date(),
    creatorId: "1",
    description: "test-description-4-2",
    lm: new Date(),
    rid: "test-rid-4-2",
    status: "closed",
    subject: "Port",
    title: "test-title-4-2",
  },
];
